- id: verify_tf_providers
  name: Verify Terraform Providers
  description: Verify that the Terraform lock file is configured for multiple platforms
  entry: hooks/verify_tf_providers.sh
  language: script
